Foreground yes
User clamav
DatabaseDirectory /var/lib/clamav
LocalSocket /tmp/clamd.sock
TCPSocket 3310
TCPAddr 0.0.0.0
ReadTimeout 30
CommandReadTimeout 10
StreamMaxLength 25M
MaxThreads 2
MaxQueue 8
MaxFileSize 25M
MaxScanSize 100M
MaxRecursion 8
MaxFiles 1000
AlertExceedsMax yes
ExitOnOOM yes
LogTime yes
